### ISSUE TITLE
Requirements: add 'bid' to relatesTo codelist

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#110]
In Paraguay, one requirement  is that the bidders must provide a guarantee to kept their offers/bids at the same price if they win. So, the requirement is about the bid itself. 
So, can we add the 'bid' code to the  relatesTo codelist?

**Comment by jpmckinney** [comment]
Just to check, is the guarantee with respect to the bid as a whole, or with respect to an item?

**Comment by jpmckinney** [comment]
Related issue: https://github.com/open-contracting/standard/issues/900 I hadn't seen the updates there yet – I'll read them now.

**Comment by yolile** [comment]
The guarantee is with respect to the bid as a whole. You have to present only one guarantee for all your bids in the tender.

**Comment by yolile** [comment]
So, should I put the requirementResponses inside the bid? As the guarantee is the same for all the bids for a given tenderer and because in an auction a bidder can have several bids, would'nt be this too much repetition?

**Comment by PaulBoroday** [comment]
> You have to present only one guarantee for all your bids in the tender.

There are cases when this is not the case: multi-lot procedures where each lot can require different guarantees.  

> So, should I put the requirementResponses inside the bid

This is the only place I guess

> would'nt be this too much repetition?

Well in each bid you have _organizationReference_ and its absolutely right. So why you shouldn't have the same approach for _requirementResonses_ ? The idea is to have a comprehensive model describing specific data-object. in our case - _bid_. 

Especially in your case 

>  an auction a bidder can have several bids

Those several will be different? So the value of _requirementResponse_ related to guarantee could be different in cases where instead of having a fixed value for the guarantee, CA requires it as a percent of the value of bid

**Comment by yolile** [comment]
Yes, in an auction all the bids of the same tenderer are differents but, the guarantee is a fixed percentage that is fixed in the tender so the percentage will be the same in all bids.
Guarantees data in auctions is just the number, type, entity, period and issue date

**Comment by jpmckinney** [comment]
Regarding options to reduce repetition, see https://github.com/open-contracting/standard/issues/893, though that is a significant change that would require an OCDS 2.0.

Although it can be the case that the guarantee is the same for all of a bidder's bids, like @PaulBoroday mentioned, if the procurement is divided into lots and if tenderers are allowed to bid on multiple lots, each lot can have different guarantee requirements, and therefore each bid would have different responses to the requirement.

This conversation is overlapping with how bids should be modelled in the context of auctions, for which I created a new issue: https://github.com/open-contracting/standard/issues/904

In that issue, I propose that auction submissions shouldn't be modelled as bids, but as something else. In that case, the guarantee would be on the bid (I don't think guarantees are among the 'features' of a bid that are modified over the course of an auction). As such, with respect to this issue, we would avoid repetition.

**Comment by jpmckinney** [comment]
In https://github.com/open-contracting/standard/issues/900 it was discussed that each requirement is implicitly about the 'bid' (unless stated otherwise). In https://github.com/open-contracting/standard/issues/900#issuecomment-517695943, I give the advantages/disadvantages of an explicit field. In short, being explicit reduces uncertainty. However, it could introduce inconsistency (if `relatedItem` or `relatedLots` is set) and is redundant with the implicit interpretation.

There don't seem to be strong feelings about reducing uncertainty, so I'll close this issue for now.
