### ISSUE TITLE
Support both unstructured and structured input for prizes

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/ocds-extensions#136]
Currently, we support the input of unstructured strings for the description of prizes in https://github.com/open-contracting-extensions/ocds_designContest_extension and [in the EU profile](https://standard.open-contracting.org/profiles/eu/master/en/forms/F12/#IV.3.1), with the string property `tender.designContest.prizes.description`.

However, we also want to support the input of structured data, with an array property (there are often several prizes to be described).

We can either:

- turn `prizes` into an array of `Prize` objects and add a `prizeDetails` string property for unstructured content
- or add an array property in `prizes` and continue using `prizes.description` for unstructured data

**Comment by jpmckinney** [comment]
What do you think?

The selection criteria extension follows the second pattern: https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension/blob/master/release-schema.json

I'm not sure if we have an example of the first pattern yet, but we often use `*Details` fields paired with a codelist field.

One concern about the second pattern is: what do we name the array field? `tender.prizes.prizes` would be weird.

**Comment by ColinMaudry** [comment]
Yes I reached the same conclusions. I'll look into it tomorrow :crescent_moon:

**Comment by jpmckinney** [comment]
I think the second pattern could make sense if we anticipate other fields on the object. However, if we only ever expect either a structured array or an unstructured string, then the first `*Details` pattern seems preferable.

For the F12 mapping, we put some 'prize'-related fields on the DesignContest object directly, like `followUpContracts` and `rewardsDetails`. If we wanted to follow the second pattern, it might have been more consistent to put them inside `prizes`.

So, I'm leaning towards a `*Details` field.

This leaves the question of whether to do anything about the other extensions. For award criteria, I think it's appropriate to group the `weightingDescription` and `orderRationale` fields within an object (rather than have many more fields with an `awardCriteria` prefix). That being the case, I think it's appropriate for selection criteria to follow the same pattern to avoid surprising users. For recurrence, it's fairly underspecified in legislation, so hard to say if we can anticipate more fields in the future. Anyway, I think it's okay to leave these as-is.

**Comment by jpmckinney** [comment]
We can perhaps add a note here once we decide on what pattern to pursue: https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#details-field

**Comment by jpmckinney** [comment]
A design contest can have follow-up contracts and rewards without prizes, so they don't belong in the `prizes` object, unless we expand its semantics (and rename the field).

After discussing with Colin, we're okay with leaving the extension as-is, as it's hard to anticipate whether there will be new 'metadata' fields to add within the `prizes` object.
