### ISSUE TITLE
Location: Geographic identifiers

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting/ocds-extensions#142]
In a lot of cases we are facing with a lack of structured information regarding the address of party, place of performance, jurisdiction and so on. To achieve more detailed and (most important) structured description of such information, could something like this be considered as a possible extension of 'Address' object?

```
{
  "address": {
    "addressDetails": {
      "addressCountry": {
        "scheme": "iso-alpha2",
        "id": "UA",
        "description": "Ukraine",
        "url": ""
      },
      "addressRegion": {
        "scheme": "iso-alpha2",
        "id": "UA-12",
        "description": "Dnipropetrovska oblast",
        "url": ""
      },
      "addressLocality": {
        "scheme": "UN/LOCDE",
        "id":"UA-DNK",  
        "description": "Dnipro",
        "url": "https://service.unece.org/trade/locode/ua.htm"
      }
    }
  }
}
```

**Comment by duncandewhurst** [comment]
@jpmckinney is this ready for a PR based on your proposed approach?

**Comment by jpmckinney** [comment]
This issue has not attracted further demand, so I would close it.

**Comment by duncandewhurst** [comment]
This issue is relevant to mapping [BT-5071 (Place Performance Country Subdivision)](https://docs.ted.europa.eu/eforms/1.0.0/schema/all-in-one.html#performancePlaceSection) from eForms, which is represented as a NUTS code. I guess it is also going to come up wherever addresses are specified in eForms.

The approach in the EU profile was to map the NUTS code to `Address.region`, e.g. [F03](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F03/) II.2.3. However, in that approach, the context that the value is a NUTS code is lost.

**Comment by jpmckinney** [comment]
I don't have a problem deferring the identification of the scheme to a publication policy. We don't have evidence of any cases where a publisher mixes multiple geographical schemes. If I look up, e.g. "UKC11" in Google, the first page of results is mostly about the NUTS location.
