### ISSUE TITLE
Bids: Corrected price

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#155]
Indonesia's [LPSE](https://lpse.lkpp.go.id/eproc4/) system collects structured data on 'bid prices' (the value originally submitted by the bidder) and 'corrected prices' (the confirmed bid value after any errors are corrected) ([example 1](https://lpse.lkpp.go.id/eproc4/evaluasi/7103119/pemenang), [example 2](https://lpse.lkpp.go.id/eproc4/evaluasi/7012119/pemenang)).

I am not sure of the exact scope of the errors that can be corrected in Indonesia's system, but the UNCITRAL model law Article 16 (2) states that:

> The procuring entity shall correct purely arithmetical errors that are discovered during the examination of submissions. 

The description of `Bid/value` doesn't specify which value should be provided, but it seems like the corrected price relates to the buyer's evaluation of the bid so, presumably, the value originally submitted by the bidder should go in `Bid/Value`.

For clarity, we should update the description of `Bid/Value`:

> The total value of the bid, as submitted by the bidder and before any corrections made during the assessment of bids.

That leaves the question of where to put the corrected price. Adding a sibling `Bid/correctedValue` field defined as follows seems like the simplest option:

> The total value of the bid, corrected for any purely arithmetical errors discovered during the assessment of bids.

@jpmckinney since you prefer not to mix the concepts of bid and bid assessment (CRM-6763) how would you suggest to model the corrected value?

cc @pindec

**Comment by jpmckinney** [comment]
In terms of workflow:

* The bid value as submitted goes in `Bid/Value`
* If a correction is made, that bid value is overwritten

OCDS' model for corrections is to overwrite previous values (though it also offers Amendment objects to further describe the change(s) in the more sensitive cases of tender/solicitation, award and contract).

Correcting a bid price is not an evaluative action; it doesn't form part of a buyer's evaluation. Indeed, in [some jurisdictions](https://www.cohenseglias.com/contracting-database/mistake-in-bid/), the bidder can submit the correction (e.g. a misplaced decimal, correcting 100,000 to 1,000,000).

So, we can just give an example in the docs of correcting a bid value. We shouldn't update the field description with e.g. "including any corrections", because in the OCDS model we would have to do that for every correctable field.

**Comment by jpmckinney** [comment]
> @jpmckinney since you prefer not to mix the concepts of bid and bid assessment (CRM-6763) how would you suggest to model the corrected value?

To be clear, it is not a matter of personal preference, but of having different mappings for different concepts :)

**Comment by duncandewhurst** [comment]
So in an 'Easy releases' model, the original bid price would be lost?

For context, this field appears in the periodic data export that ICW get from LPSE which they then wish to publish in OCDS format. So they don't really see that workflow, rather they get some awards data which includes both the original and corrected values.

**Comment by jpmckinney** [comment]
Yes – like all other values before corrections in that model.

ICW can either generate two releases in that case (the second release could be very small as it only includes the correction) to emulate how it would have been published at source, or it can discard the original value.
