### ISSUE TITLE
requirements: Remove requirementResponses from awards, contracts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#190]
There is no reason to have these alternative ways of disclosing the same facts that are appropriately disclosed using bids.

Even if a publisher is not making full use of the bids extension, they can still fill in a small Bid object for the winning bid.

**Comment by jpmckinney** [comment]
All requirementResponses were added at once in this commit: https://github.com/open-contracting-extensions/ocds_requirements_extension/commit/82c4fb1811a02096417aa0a921bd3fb093aeeae1 I can find no justification for the additions to Award and Contract in https://github.com/open-contracting/standard/issues/379 or https://github.com/open-contracting/standard/issues/223. I don't know if @duncandewhurst remembers?

**Comment by duncandewhurst** [comment]
I don't remember specifically. My best guess is that it was to allow for the possibility that requirement responses might vary  between bids, awards and contracts, due to negotiation, for example. However, I don't think we've seen these fields used in practice so I have no objection to removing them.

**Comment by yolile** [comment]
Hmm, the extension also says that the response source could be from buyers and procuring entities. But where should these responses be disclosed?

**Comment by jpmckinney** [comment]
>  Where this requirement response relates to a tenderer and is provided by the buyer or procuring entity this field should be used to reference the entry in the parties section for the tenderer the response relates to.

I don't understand the part about "and is provided by the buyer or procuring entity". It's not explained in the only discussion of `relatedTenderer`: https://github.com/open-contracting/standard/issues/223

In 223, `relatedTenderer` is only used within a Bid object, and bids are provided by bidders.

I guess `relatedTenderer` exists, because a Bid object can have multiple `tenderers`. This feels a bit like over-engineering, as most bids are by individual organizations. For consortia, I don't know if buyers require responses from each consortium member, or if they have instructions on how to provide a single answer to questions of annual turnover, years active, etc. (e.g. sum together or take the average/maximum/minimum value).

I would at minimum remove the confusing words, and maybe remove the field unless we have evidence of its use.

**Comment by yolile** [comment]
The documentation says 

> Criteria can be responded to either by bidders, buyers or procuring entities, for example a buyer may respond with information about an item whilst a procuring entity may respond with information on whether a bidder is disbarred.

So I guess the logic is, for example, if the requirement is a certification, and the certification is registered in the suppliers' register the buyer/procuring entity can reply to that requirement as part of the tenderer bid requirement response? And maybe it could exist a post-bid requirement that could be responded to during the award phase? Although if the requirement is post-bid, I guess it would be more contract terms rather than selection/criteria/technical specifications (but the extension name is requirements and "selection criteria" or "technical specification" terms are not used as part of the extension)

**Comment by jpmckinney** [comment]
> Criteria can be responded to either by bidders, buyers or procuring entities, for example a buyer may respond with information about an item whilst a procuring entity may respond with information on whether a bidder is disbarred.

I'm not aware that any buyer/procuring entity ever does this. If the requirements extension is used to model exclusion grounds (as [anticipated](https://github.com/open-contracting/standard/issues/223#issuecomment-292988204)), then a supplier must respond as to whether or not they pass the exclusion grounds. If they lie, they can be penalized (fine, etc.). The buyer can of course do due diligence to check answers, but the buyer is not providing the response.

If the information is stored in a supplier registry, it is still being provided by the supplier (who originally provided it).

I can't think of an example where a buyer responds to an item's requirement.

Post-bid requirements are a different thing and might just fall under implementation.

**Comment by yolile** [comment]
> I can't think of an example where a buyer responds to an item's requirement.

Me neither.

Should we remove/deprecate the `source` field as part of this PR?

**Comment by jpmckinney** [comment]
> Source of response to the requirements specified in the criterion. For example, responses might be submitted by tenderers or by an assessment committee at the procuringEntity.

[responseSource codelist](https://extensions.open-contracting.org/en/extensions/requirements/master/codelists/#responseSource.csv)

Yes, I'm not aware of any jurisdiction having a committee respond to selection criteria/exclusion grounds. There are more often committees for award criteria, but again I don't know that any provided a structured breakdown of their evaluation.

**Comment by yolile** [comment]
> I don't know that any provided a structured breakdown of their evaluation.

I know one [example](https://comprar.gob.ar/EVALUACIONOFERTA/PreAdjudicarVisualizarDictamen.aspx?qs=%7Cc3sc8YiU%7Crolrc9OrzYVtq60tGYIlP1inIXJk9B6TYc0jawx12aTSyC/mWIxwU05bxWgRCUEKvrLNq4TnCDUyCpsAsL5ewMe1QDdSQnUtW7oYUPDw4r6cdinl6Z74iNnpaBlEDeagZ/cW5Az4SHmhDnbGgH6i3wibh4VRlVqbgl4OP4QydMUSGPA41agvLUakhJQ%7CEUt0pDT8Mzb%7CXrP4DP5tiooKUemC6MgKSYVbwN0jHuc1uIM5Pn20r%7CVIqdIWfMcT%7CDVqPzESJgYnpt2MzdLfEwj3hsVtW9WqCrNjmdNC9hoPnWfayoi4bUqnoKmgzae2DGvML3eul2ywoIybRr69mtBzAtwNSDIKAnfY3U/lakADLA/g==), Argentina. They disclose a "Dictamen de Evaluación de Ofertas" (Bid Evaluation Resolution) (They call this a "pre-award" stage). This example can mainly be modeled with bid status. Still, in the "Ofertas desestimadas" section, they also provide some details about the price evaluation, e.g., "Precio excesivo en 300%" (price is 300% higher) and the technical evaluation (in that particular example, that column is empty because all of the bids were disqualified for price reasons only), for each item ("renglón") and tenderer.

But I guess, in this case, the committee is evaluating the bidders' response (both technical and monetary) but not responding to a requirement themselves.

**Comment by jpmckinney** [comment]
Interesting – anyway, that'd be for a new extension for evaluation against award criteria :)

**Comment by yolile** [comment]
And just for the record, [here](https://comprar.gob.ar/EVALUACIONOFERTA/PreAdjudicarVisualizarDictamen.aspx?qs=|c3sc8YiU|rolrc9OrzYVtq60tGYIlP1inIXJk9B6TYc0jawx12aTbiDO2q3QmWkytSua2KbjOI4jybJU8j6VD0zuZMShHbiFtFvXw3l1dP2cj4KU6qH1O8CNPXu9KJvwbXXeDbY/NM6v19LnzaBcZWfZBoGbwaKK2eyWaRyidUO4brJbmDgAOgmJ5s89RF1D8ntT6IQ0Mas7EEO6/0S0g5PquU/bv2MBOxTOEsE5mLmkpdqpbfK0tARRJb//r7ZIbf5nOfwiPFzywoqI4fmM3EO8N2BK1Z2b2DVpTc2I5tCU1Fy8ifDEA==) I found another example where they also put the technical evaluation and the administrative evaluation (both free texts and without a reference to the specific technical or administrative requirement). Note that I think these are requirements rather than award criteria. E.g., one technical evaluation says, "Regarding the technical specifications of the equipment offered, it does not comply with the requested certifications (Mil-Spec Test, EPEAT™ Gold, RoHS compliant, etc.)." And note that they only provide these evaluations for the disqualified bids. (So this could be understood as "disqualification rationale"). Or, I guess, If we follow the current requirements extension logic, this should be under `bids/requirementResponses`. But as you said, even for this case, the requirement (or, in the example, the lack of compliance with the requirement) is still something provided (or not) by the bidder, and the buyer just checks it.

**Comment by jpmckinney** [comment]
Yes, the buyer sets the requirements, and then the bidders respond to them. If the buyer is not satisfied with the response, or finds an error in the response, the buyer is not "responding" to the requirement - they are doing something else, which needs to be modelled separately.

**Comment by jpmckinney** [comment]
For context, selection criteria and award criteria are separated, since a two-stage process might first evaluate requests to participate against selection criteria, then invite bids, and evaluate those against award criteria.

In these two Argentina examples, it seems like they are single-stage processes, and so both types of criteria are evaluated at once. I anticipate that the Evaluación Técnica can sometimes fail based on criteria that would typically be selection. The Evaluación Económica seems to be skipped if the Evaluación Técnica fails (like in a two-stage process). An Evaluación Económica, though, is always an award criterion, I'm pretty sure.

**Comment by yolile** [comment]
Aha. In any case, I created a separate issue to discuss more the bids evaluation disclosure https://github.com/open-contracting/standard/issues/1546.

**Comment by jpmckinney** [comment]
Using https://ocdsdata.fra1.digitaloceanspaces.com/metadata/stats.json

* No publisher uses requirementResponses, so they are okay to remove from awards and contracts.
* moldova uses relatedTenderer. 
* moldova uses source.

I think it's okay for the fields to be removed, which results in moldova having two more additional fields.

**Comment by jpmckinney** [comment]
Closed by above commit.
