### ISSUE TITLE
Finance: Add field to identify concessional finance

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#206]
I'm looking at reusing the modelling from the finance extension to model the following climate finance data point from the OC4IDS review:

> **Financial instrument**
> Disclose the financial instrument type from the list:
> - loan
>   - concessional
>   - non-concessional
> - grant
> - equity
> - guarantees

With the exception of dividing loans into concessional/non-concessional, these options broadly map to the [finance category codelist](https://extensions.open-contracting.org/en/extensions/finance/master/codelists/#financeCategory.csv):

* loan: seniorDebt or mezzanineDebt
* grant: grant
* equity: equity
* guarantees: guarantee

The World Bank [describes](https://www.worldbank.org/en/news/feature/2021/09/16/what-you-need-to-know-about-concessional-finance-for-climate-action) concessional finance as follows:

> Put simply, concessional finance is below market rate finance provided by major financial institutions, such as development banks and multilateral funds, to developing countries to accelerate development objectives. [The term concessional finance does not represent a single mechanism or type of financial support but comprises a range of below market rate products used to accelerate a climate or development objective.](https://www.worldbank.org/en/news/feature/2021/09/16/what-you-need-to-know-about-concessional-finance-for-climate-action#)

Rather than adding new codes to the finance category codelist for concessional and non-concessional debt financing, I think it would make more sense to add a new field based on the World Bank's description:

Path | Title | Description | Type
-- | -- | -- | --
`Finance.concessional` | Concessional | Whether the finance is provided below market rate in order to accelerate climate or development objectives. | Boolean

**Comment by jpmckinney** [comment]
## Model

From the linked page:

> The most common financial products used to deliver concessional finance come in the form of loans, grants and, to some extent, equity investments

So, definitely makes sense to add as a separate field. 

## Style

Should we use the phrase "the financing" rather than "the finance"? We use "the finance" in `financeCategory` but "the financing" elsewhere.

## Description

> Whether the finance is provided below market rate in order to accelerate climate or development objectives.

Looking at the WBG description with some others:

* concessional finance is below market rate finance provided by major financial institutions, such as development banks and multilateral funds, to developing countries to accelerate development objectives. (World Bank)
* Concessional loans, or soft loans, have more generous terms than market loans. These generally include below-market interest rates, grace periods in which the loan recipient is not required to make debt payments for several years or a combination of low interest rates/grace periods. ([USAID](https://www.usaid.gov/energy/mini-grids/financing/grants#:~:text=Concessional%20loans%20%2C%20or%20soft%20loans,low%20interest%20rates%2Fgrace%20periods.))
* The term 'Concessional Finance' is used (among others, such as soft financing, subsidised funding, etc) to refer to all the financial and tax instruments made available to businesses by lawmakers to encourage new development and investment projects. ([WarrantHub](https://www.warranthub.it/en/services/concessional-finance/))
* is concessional in character. In DAC statistics, this implies a grant element of at least [##] per cent ([OECD](https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/officialdevelopmentassistancedefinitionandcoverage.htm))

The definitions align. OECD adds a little wrinkle, in that a concessional loan pairs a grant with a loan, such that the *effective* rate is below market (by averaging the loan's rate with the grant's rate, which is by definition 0%). I don't think we need to capture this detail. They do this so that they can measure the grant's share of the financing.

USAID allows for concessional loans to be only characterized by grace periods, but I know plenty of conventional loans that have grace periods – I think we should stick with the below market rate description.

So, in brief, the first sentence is good.

We can maybe add a second sentence with alternative names like we do for some fields/codes in OCDS: 

> This is also called soft financing and and subsidized funding.

**Comment by duncandewhurst** [comment]
All sounds good. Thanks for the feedback!

I'll hold fire on creating a PR until the climate finance data points are finalised, in case something changes.

**Comment by duncandewhurst** [comment]
Regarding the style note, in https://github.com/open-contracting/ocds-extensions/issues/207#issuecomment-1802732480, I've used "financing arrangement" so I suggest that we align with that:

> Whether this financing arrangement is provided below market rate in order to accelerate climate or development objectives. This is also called soft financing and subsidized funding.

**Comment by duncandewhurst** [comment]
Regarding the style note, in https://github.com/open-contracting/ocds-extensions/issues/207#issuecomment-1802732480, I've used "financing arrangement" so I suggest that we align with that:

> Whether this financing arrangement is provided below market rate in order to accelerate climate or development objectives. This is also called soft financing and subsidized funding.

@evelyndinora, @mgraca-prado - are you happy with the proposal in this issue?

**Comment by EvelynDinora** [comment]
Yes, I am happy with it. Thanks @jpmckinney and @duncandewhurst
