### ISSUE TITLE
EU: add foreignSubsidyMeasureConclusion string field to bids.details

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#233]
see https://github.com/open-contracting/european-union-support/issues/219 for discussion about need for this field.

@jpmckinney do you think it is worth making this a codelist with the [Foreign Subsidy Measure Conclusion](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/foreign-subsidy-measure-conclusion) codes (similar to what we've done for `SelectionCriteria.sources` in https://github.com/open-contracting-extensions/ocds_eu_extension/pull/18 or just leave it as free-text?

**Comment by jpmckinney** [comment]
Might as well use the codelist, to match the expected mapping.

**Comment by jpmckinney** [comment]
I am debating whether to name it "foreignSubsidyMeasures" since field is defined as "Measures applied under the Foreign Subsidies Regulation (EU) 2022/2560." and the codelists's _Dataset details_ has "This code list is about the situation of Measures applied under the Foreign Subsidies Regulation (EU) 2022/2560. "
