### ISSUE TITLE
bid: Add descriptions to the bid status codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#24]
Currently this codelist is missing descriptions

**Comment by duncandewhurst** [comment]
Assigning to @timgdavies as original author of the codelist

**Comment by duncandewhurst** [comment]
This request was prompted by a question from @dwasyl on the definition of the `invited` code, here's the guidance I shared and some feedback from David:

> I believe the invited status is for a limited procedure type, i.e. where the procuring entity contacts a number of suppliers of it's choice to invite bids, in which case the bids may be invited prior to being pending (submitted).

> invited for bids makes some sense in that context, although even on an invitational tender I'm not sure if you'd create a bid/bidder record of just an invitation. Being invited doesn't really make you necessarily willing to bid - although it could be helpful to know how many were invited vs actually bid.

**Comment by timgdavies** [comment]
I'm staging the following definitions. 

* Invited - A bid has been invited from the listed tenderer(s).
* Pending - A bid has been submitted but not yet evaluated.
* Valid - A bid has been submitted and meets the requirements in order to be evaluated.
* Disqualified - The submitted bid did not meet the qualification requirements and so will not be evaluated.
* Withdrawn - The submitted bid was withdrawn by the tenderer(s).

**Comment by jpmckinney** [comment]
For Valid, to be more consistent in wording with Disqualified and Withdrawn, should it be:

**The submitted bid meets the qualification** requirements in order to be evaluated.

And for Disqualified to be consistent with Valid:

The submitted bid did not meet the qualification requirements **in order to** be evaluated.

**Comment by timgdavies** [comment]
I'd be happy with these changed wordings.
