### ISSUE TITLE
apiExtension packageMetadata in compiledRelease

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#67]
When two or more releases from differents publishers are compiled in a compiledRelease how could the meta information from both publishers be included in the compiledRelease? Maybe the packageMetadata should be an array instead of an object?

**Comment by jpmckinney** [comment]
Related to this tag: https://github.com/open-contracting/standard/labels/Focus%20-%20Publishing

**Comment by yolile** [comment]
@jpmckinney  Honduras goverment is going to publish information from two differents publishers, and then another entity is going to generate and publish the compile release. is it better to create a new extension with the publisher field as an array or update this one?

**Comment by duncandewhurst** [comment]
@yolile see comments from @jpmckinney in https://github.com/open-contracting/api-specification/issues/15

**Comment by jpmckinney** [comment]
There are many ways we can possibly do this.

Using just core OCDS, you can do: The `publisher` of the record package is the entity that generates the compiled release. The `packages` of the record package links to the release packages of the other two publishers; those release packages have `publisher` set to those publishers.

For OCDS 1.2, I'm thinking that `publisher` should be a field on the release, not on the package, which will also resolve this issue. https://github.com/open-contracting/standard/issues/325#issuecomment-445892448 The semantics for `publisher` on the compiled release might be that it's whoever publishes the compiled release, instead of following the regular merge rules (relevant to https://github.com/open-contracting/standard/issues/330).

As for the API extension, I think there are issues with it. I don't think we should recommend it here. As in the comment Duncan linked to, most of the package metadata makes no sense at the release-level.

So, for Honduras, I think the best option is to just use core OCDS as described above.

**Comment by jpmckinney** [comment]
Closing in favor of open issues on other repos.
