### ISSUE TITLE
Bids, Enquiry: Merge behavior

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#77]
The following fields behave as `wholeListMerge`. I'm not sure that this is correct.

* Bids: `Bid.tenderers` and `Bids.statistics` have `"type": ["array", "null"]`, which means implicitly that they are `wholeListMerge`.
* Enquiry: `Tender.enquiries` has `"type": ["array", "null"]`, which means implicitly that it is `wholeListMerge`. `Enquiry.id` is optional and nullable, which is consistent with that.

~~I have PRs below for additionalContactPoints, exchangeRate, and recurrence, which have arrays of objects that lack `id` fields (ContactPoint, ExchangeRate, Period). `wholeListMerge` isn't technically required, but I think it's better to be explicit.~~ (Changes merged)

I staged a PR for enquiry, but as mentioned, I'm not sure it's correct.

**Comment by jpmckinney** [comment]
Note to remove some exceptions from test_json.py if we change the behavior in bids.

**Comment by jpmckinney** [comment]
@duncandewhurst Please share your opinion on the merging behavior for bids and enquiries, described above.

**Comment by duncandewhurst** [comment]
`bids.tenderers` - I agree, I can't see why it should be merged differently than `tender.tenderers`(which is identifier merge) - though noting that until https://github.com/open-contracting/standard/issues/679 is resolved in 2.0 then `id` on `organization` isn't required, so it could be possible to have valid data that couldn't merged with identifier merge

`bids.statistics` - I agree, since `BidsStatistic.id` is required and should be a unique in the scope of the array there's no reason for it to be whole list merge and looking at the bid statistics codelist it's conceivable that individual bid statistics could be added at different times (i.e. 'bids' and 'validBids') so identifier merge would make more sense for that case

`tender.enquiries` - I wasn't able to find any documentation of why this should behave as whole list merge and intuitively since there may be multiple rounds of enquiries or threaded conversations, it seems to me that identifier merge would make more sense, though making `id` required would be a backward incompatible change on a recommended extension, so for now we could make wholelist merge explicit and add an issue for making it identifier merge to the 2.0 milestone

**Comment by jpmckinney** [comment]
If the `id` is missing, that object is simply kept when merged (but with no way to update it in new releases), in OCDS Merge 0.5. (In OCDS Merge 0.4, the behavior was to overwrite a non-`id` object with any new object at the same index in the array, which was less predictable.)

I'll change `bids.tenderers` and `bids.statistics` to use identifier merge.

I'll create an issue for enquiries and leave it as implicit for now.

**Comment by jpmckinney** [comment]
https://github.com/open-contracting-extensions/ocds_bid_extension/commit/1ddf042d82a131027e82159873d3148e73aa9b2d
